---
title: "Tilapia"
author: "Jessica French"
date: "2022-08-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(janitor)
```

```{r}
us_tilapia_imports <- read_csv(here::here("data", "us_tilapia_imports.csv"))
```

```{r}
summary(us_tilapia_imports)
dim(us_tilapia_imports)
skimr::skim(us_tilapia_imports)
```

```{r}
us_tilapia_imports_long <-  us_tilapia_imports |> pivot_longer(
                                        cols = -country, 
                                        names_to = "year", 
                                        values_to = "export_vol") |> 
mutate(year = as.numeric(year))
```


```{r}
tilapia_tot <- us_tilapia_imports_long |> 
  group_by(year) |>   
  summarize(total_vol = sum(export_vol, na.rm = TRUE))
```


```{r}
plot <- ggplot(data = tilapia_tot, 
               aes(x = year,
                   y = total_vol)) +
  geom_line() +
  labs(x = "year",
       y = "Total import volume in thousands of pounds")

plot

ggsave(here::here("figs", "tilapia_import_plot.png"))
```


```{r}
tilapia_export_countries <- us_tilapia_imports_long |> 
  filter(country %in% c("Ecuador", "Honduras", "Costa Rica", "Mexico")) 
  
```

```{r}
plot_country <- ggplot(data = tilapia_export_countries, 
                       aes(x = year, 
                           y = export_vol)) +
  geom_line(aes(color = country)) 
  #facet_wrap(~country)

plot_country

ggsave(here::here("figs", "import_plot_country.png"))
```

